feature: Начал описание модели заявки
HRSpaceX/backend pull request #2
Opened 2024-03-14 18:02 UTC by yan-gabala

Проведите ревью, Напишите замечания. Устраним недостатки. После этого одобрите мердж.

2024-03-14 18:51 UTC, hydrospirt requested changes
Отличное начало, несколько правок написал, свои мысли и комментарии к коду

2024-03-14 18:51 UTC, hydrospirt commented on hrspace/bid/models.py
> +    city = models.CharField(
Точно не знаю, но может вынести город в отдельную модель, чтоб хранить их в базе данных?
Просто если планировать, что приложение будет расширятся, то лучше хранить в БД, а не в оперативной памяти. Быть может, к городам будет добавляться, какая то дополнительная информация в будущем

2024-03-14 18:51 UTC, hydrospirt commented on hrspace/bid/models.py
> +class ApplicationForm(models.Model):
Модель называется формой, это может вызвать путаницу. У себя назвал просто Order, т.е. конечный продукт хранящийся в БД  является заявкой для исполнения, а не является формой

2024-03-14 18:51 UTC, hydrospirt commented on hrspace/bid/models.py
> +from .constants import (NAME_MAX_LEN, CITY_CHOICES,
Константы в отдельном файле это отличное решение + с самого начала написания кода.
Но лучше использовать полный импорт

2024-03-14 18:51 UTC, hydrospirt commented on hrspace/bid/models.py
> +    salary = models.PositiveIntegerField(
Да, круто, я тоже сделал это поле PositiveIntegerField. Но у нас в ответе будет приходить salary_from и salary_to. Я никогда не работал с NoSQL базами, такую информацию проще в них хранить, вроде как в интернете прочитал. Здесь если честно, сам думаю, но пока 2 поля

2024-03-14 18:51 UTC, hydrospirt commented on hrspace/bid/constants.py
> +PROFESSION_CHOICES = [
Здесь, тоже нужно подумать. Судя по HH  у них что-то типо:
класс Сфера -> класс Профессия, ну например:
Информационные Технологии -> Аналитик Данных
Производство -> Швея
Я к тому, что если расширять приложение вариант с выбором не подойдет

2024-03-14 18:51 UTC, hydrospirt commented on .gitignore
> +temp.json
Что в этом файле? :)

2024-03-15 06:48 UTC, yan-gabala commented on hrspace/bid/models.py
> +from .constants import (NAME_MAX_LEN, CITY_CHOICES,
Полный импорт, как фичу давай позже. Я не знаю как это

2024-03-15 06:49 UTC, yan-gabala commented on hrspace/bid/models.py
> +    salary = models.PositiveIntegerField(
Через валидаторы огран сделаю на 2 поля

2024-03-15 06:51 UTC, yan-gabala commented on hrspace/bid/constants.py
> +PROFESSION_CHOICES = [
Можно эти вопросы вынести на доску Кaiten - там они не потеряются и будет виден прогресс по ним

2024-03-15 06:52 UTC, yan-gabala commented on .gitignore
> +temp.json
джэйсон от фронта

2024-03-15 06:56 UTC, yan-gabala commented on hrspace/bid/models.py
> +    city = models.CharField(
Согласен

Можно эти вопросы вынести на доску Кaiten - там они не потеряются и будет виден прогресс по ним.

2024-03-15 06:57 UTC, yan-gabala commented on hrspace/bid/models.py
> +class ApplicationForm(models.Model):
Ок

2024-03-15 15:40 UTC, closed without merging

2024-03-15 15:41 UTC, yan-gabala commented
Надо поменять main dev