feature: Создание модели заявки + создание файла constants
HRSpaceX/backend pull request #3
Opened 2024-03-14 19:53 UTC by JuliSem

Создала модель заявки + файл constants.py
Поля модели сделала в соответствии с примерами страниц, которые составили дизайнеры в фигме(отметила комментариями 1.1, 1.2, 1.3 и т.д.)
Есть вопросы по некоторым полям в моделях:
1) "Сфера деятельности" - выбираем из списка, вот только где его взять
2) "Город" - тоже выбираем из списка. Нашла в интернете библиотеку django-cities-light, при её установке доступен список городов, но они высвечиваются все на английском языке. Вот ссылка на источник https://medium.com/@FatemeFouladkar/how-to-add-country-and-city-field-in-django-864f80b4c19e
3) "Заработная плата" - не поняла, как сделать так, чтобы высвечивались 2 поля("от" и "до"), как на слайде в фигме у дизайнеров
4)"График работы" - та же проблема как и в "заработной плате"
В некоторых полях должна быть возможность выбора нескольких позиций, но это вроде можно настроить в сериализаторе.

2024-03-14 20:45 UTC, 1517mb requested changes
Отличная работа, но многое предстоит ещё обсудить

2024-03-14 20:45 UTC, 1517mb commented on hrspace/bid/models.py
> +class Application(models.Model):
Нам нужно совместно придумать название модели :)
И когда всё храниться в одной модели, это сильно перегружает читаемость кода, можно подумать, командой, как сделать красиво

2024-03-14 20:45 UTC, 1517mb commented on hrspace/bid/models.py
> +    salary = models.DecimalField("Заработная плата",
Почему зарплата в Decimal?

2024-03-14 20:45 UTC, hydrospirt commented on hrspace/hrspace/constants.py
> +    ("employment_record", "Оформление по ТК"),
Меня всегда поражает фраза в преимуществах работы Оформление по Трудовому кодексу, это только в России так... и наличие "Отпуска". Я бы убрал это в обще из преимуществ работодателя. Потому что это должно быть по умолчанию.

2024-03-14 20:45 UTC, hydrospirt commented on hrspace/bid/models.py
> +    vacancy = models.CharField("Название вакансии",
vacancy_name или name(название)?

2024-03-15 07:18 UTC, yan-gabala commented on hrspace/bid/migrations/0001_initial.py
Миграции в гитигнор

2024-03-15 07:18 UTC, yan-gabala commented on hrspace/bid/models.py
> +class Application(models.Model):
Я обобщу в своей ветке ваши , потом смерджу в dev
Далее малыми итерациями добавляем фичи небольшие

2024-03-15 07:18 UTC, yan-gabala commented on hrspace/bid/models.py
Отлично, все поля заявки описаны!

2024-03-15 07:18 UTC, yan-gabala commented on hrspace/hrspace/constants.py
Константы ВАУ!

2024-03-15 07:18 UTC, yan-gabala commented on hrspace/hrspace/settings.py
Давайте с городами кто-нибудь возьмет как фичу и добавит
Пока оставлю для тестов тверь и псков

2024-03-15 07:18 UTC, yan-gabala commented on requirements.txt
Давайте с городами кто-нибудь возьмет как фичу и добавит
Пока оставлю для тестов тверь и псков

2024-03-15 07:18 UTC, yan-gabala commented on vevn/Scripts/Activate.ps1
В гитигнор

2024-03-15 08:32 UTC, JuliSem commented on hrspace/hrspace/constants.py
> +    ("employment_record", "Оформление по ТК"),
Так было в примере на слайде у дизайнера)) Но можно убрать)

2024-03-15 08:32 UTC, JuliSem commented on hrspace/bid/models.py
> +    vacancy = models.CharField("Название вакансии",
можно vacancy_name

2024-03-15 08:39 UTC, JuliSem commented on hrspace/bid/models.py
> +    salary = models.DecimalField("Заработная плата",
Думала, что для денег лучше использовать этот тип, но можно и PositiveIntegerField)

2024-03-15 18:50 UTC, hydrospirt commented
Закрываю ветку, нужно будет сделать новую ветку от dev, когда настрою

2024-03-15 18:50 UTC, closed without merging